version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
